/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import ClasesObjetos.Habitacion;
import ClasesObjetos.Hotel;
import java.util.List;

public class VistaCiudad extends javax.swing.JFrame {
    
    private LandingPage lp;
    private VistaHotel vh;
    public Hotel[] hoteles;
    
    public LandingPage getLp() {
        return lp;
    }

    public void setLp(LandingPage lp) {
        this.lp = lp;
    }
    public VistaHotel getVh() {
        return vh;
    }

    public void setVh(VistaHotel vh) {
        this.vh = vh;
    }
    /**
     * Creates new form Ciudad
     */
    public VistaCiudad() {
        initComponents();
        
        this.vh = new VistaHotel();
        this.vh.setVc(this);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RegresarBtn = new javax.swing.JButton();
        Icono = new javax.swing.JPanel();
        Inicial = new javax.swing.JLabel();
        CorreoUser = new javax.swing.JLabel();
        NombreCiudad = new javax.swing.JLabel();
        DescripcionCiudad = new javax.swing.JLabel();
        Alojamientos = new javax.swing.JLabel();
        NumHotelesEncontrados = new javax.swing.JLabel();
        Panel2 = new javax.swing.JPanel();
        NombreHotel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        LabelNro2 = new javax.swing.JLabel();
        BtnHotel2 = new javax.swing.JButton();
        DescripcionHotel2 = new javax.swing.JLabel();
        NroHabitacionesHotel2 = new javax.swing.JLabel();
        Panel1 = new javax.swing.JPanel();
        NombreHotel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        NroHabitacionesHotel1 = new javax.swing.JLabel();
        BtnHotel1 = new javax.swing.JButton();
        DescripcionHotel1 = new javax.swing.JLabel();
        Label13 = new javax.swing.JLabel();
        Panel3 = new javax.swing.JPanel();
        NombreHotel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        LabelHabitacion3 = new javax.swing.JLabel();
        BtnHotel3 = new javax.swing.JButton();
        DescripcionHotel3 = new javax.swing.JLabel();
        NroHabitacionesHotel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1200, 900));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1180, 1200));

        jPanel3.setBackground(new java.awt.Color(62, 120, 233));
        jPanel3.setPreferredSize(new java.awt.Dimension(1200, 168));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WonderLustReserve");

        RegresarBtn.setText("Regresar");
        RegresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarBtnActionPerformed(evt);
            }
        });

        Icono.setBackground(new java.awt.Color(148, 152, 242));

        Inicial.setBackground(new java.awt.Color(255, 255, 255));
        Inicial.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Inicial.setText("I");

        javax.swing.GroupLayout IconoLayout = new javax.swing.GroupLayout(Icono);
        Icono.setLayout(IconoLayout);
        IconoLayout.setHorizontalGroup(
            IconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(Inicial)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        IconoLayout.setVerticalGroup(
            IconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Inicial)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        CorreoUser.setBackground(new java.awt.Color(255, 255, 255));
        CorreoUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CorreoUser.setForeground(new java.awt.Color(255, 255, 255));
        CorreoUser.setText("Correo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(Icono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CorreoUser)
                .addGap(85, 85, 85))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(RegresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Icono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(CorreoUser)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        NombreCiudad.setBackground(new java.awt.Color(255, 255, 255));
        NombreCiudad.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        NombreCiudad.setText("Nombre de la Ciudad");

        DescripcionCiudad.setBackground(new java.awt.Color(255, 255, 255));
        DescripcionCiudad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Alojamientos.setBackground(new java.awt.Color(255, 255, 255));
        Alojamientos.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        Alojamientos.setText("Alojamientos Encontrados:");

        NumHotelesEncontrados.setBackground(new java.awt.Color(255, 255, 255));
        NumHotelesEncontrados.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        NumHotelesEncontrados.setText("3");

        Panel2.setBackground(new java.awt.Color(255, 255, 255));
        Panel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        NombreHotel2.setText("Nombre del Hotel");

        jPanel7.setBackground(new java.awt.Color(118, 124, 127));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        LabelNro2.setText("Habitaciones disponibles: ");

        BtnHotel2.setBackground(new java.awt.Color(11, 59, 89));
        BtnHotel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnHotel2.setForeground(new java.awt.Color(255, 255, 255));
        BtnHotel2.setText("Ver Hotel");
        BtnHotel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHotel2ActionPerformed(evt);
            }
        });

        DescripcionHotel2.setText("<html>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</html>");

        NroHabitacionesHotel2.setBackground(new java.awt.Color(255, 255, 255));
        NroHabitacionesHotel2.setText("#");

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreHotel2)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addComponent(LabelNro2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NroHabitacionesHotel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addComponent(DescripcionHotel2, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnHotel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addComponent(NombreHotel2)
                        .addGap(18, 18, 18)
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNro2)
                            .addComponent(NroHabitacionesHotel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DescripcionHotel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnHotel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        Panel1.setBackground(new java.awt.Color(255, 255, 255));
        Panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        NombreHotel1.setBackground(new java.awt.Color(255, 255, 255));
        NombreHotel1.setText("Nombre del Hotel");

        jPanel8.setBackground(new java.awt.Color(118, 124, 127));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        NroHabitacionesHotel1.setBackground(new java.awt.Color(255, 255, 255));
        NroHabitacionesHotel1.setText("#");

        BtnHotel1.setBackground(new java.awt.Color(11, 59, 89));
        BtnHotel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnHotel1.setForeground(new java.awt.Color(255, 255, 255));
        BtnHotel1.setText("Ver Hotel");
        BtnHotel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHotel1ActionPerformed(evt);
            }
        });

        DescripcionHotel1.setBackground(new java.awt.Color(255, 255, 255));
        DescripcionHotel1.setText("<html>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</html>");

        Label13.setBackground(new java.awt.Color(255, 255, 255));
        Label13.setText("Habitaciones disponibles: ");

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreHotel1)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addComponent(Label13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NroHabitacionesHotel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addComponent(DescripcionHotel1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnHotel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addComponent(NombreHotel1)
                        .addGap(18, 18, 18)
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label13)
                            .addComponent(NroHabitacionesHotel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnHotel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DescripcionHotel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        Panel3.setBackground(new java.awt.Color(255, 255, 255));
        Panel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        NombreHotel3.setText("Nombre del Hotel");

        jPanel9.setBackground(new java.awt.Color(118, 124, 127));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        LabelHabitacion3.setText("Habitaciones disponibles: ");

        BtnHotel3.setBackground(new java.awt.Color(11, 59, 89));
        BtnHotel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnHotel3.setForeground(new java.awt.Color(255, 255, 255));
        BtnHotel3.setText("Ver Hotel");
        BtnHotel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHotel3ActionPerformed(evt);
            }
        });

        DescripcionHotel3.setText("<html>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</html>");

        NroHabitacionesHotel3.setBackground(new java.awt.Color(255, 255, 255));
        NroHabitacionesHotel3.setText("#");

        javax.swing.GroupLayout Panel3Layout = new javax.swing.GroupLayout(Panel3);
        Panel3.setLayout(Panel3Layout);
        Panel3Layout.setHorizontalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreHotel3)
                    .addGroup(Panel3Layout.createSequentialGroup()
                        .addComponent(LabelHabitacion3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NroHabitacionesHotel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel3Layout.createSequentialGroup()
                        .addComponent(DescripcionHotel3, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnHotel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel3Layout.setVerticalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel3Layout.createSequentialGroup()
                        .addComponent(NombreHotel3)
                        .addGap(18, 18, 18)
                        .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelHabitacion3)
                            .addComponent(NroHabitacionesHotel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DescripcionHotel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnHotel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DescripcionCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 1029, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreCiudad)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NumHotelesEncontrados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Alojamientos))
                    .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(NombreCiudad)
                .addGap(18, 18, 18)
                .addComponent(DescripcionCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alojamientos)
                    .addComponent(NumHotelesEncontrados))
                .addGap(79, 79, 79)
                .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(Panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnHotel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHotel2ActionPerformed
        this.vh.NombreHotel.setText(NombreHotel2.getText());
        String nombreBuscado = NombreHotel2.getText(); // Obtener el nombre del hotel a buscar
        List<Habitacion> habitacionez = null;
        Hotel hotelEncontrado = null; // Variable para almacenar la referencia al hotel encontrado

        // Buscar el hotel en el arreglo
        for (Hotel hotel : hoteles) {
            if (hotel.getNombre().equals(nombreBuscado)) {
                hotelEncontrado = hotel;

                break; // Salir del bucle si se encontró el hotel
            }
        }
        // Verificar si se encontró el hotel
        if (hotelEncontrado != null) {
            // Se encontró el hotel, puedes utilizar las habitaciones de ese hotel
            habitacionez = hotelEncontrado.getHabitaciones();
        }
        
        this.vh.habitaciones = habitacionez;
        this.vh.DescripcionHotel.setText(DescripcionHotel2.getText());
        this.vh.CorreoUser.setText(CorreoUser.getText());
        this.vh.Inicial.setText(Inicial.getText());
        
        this.vh.setVisible(true);
        this.vh.setLp(this.lp);
        this.setVisible(false);
    }//GEN-LAST:event_BtnHotel2ActionPerformed

    private void BtnHotel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHotel1ActionPerformed
        String nombreBuscado = NombreHotel1.getText(); // Obtener el nombre del hotel a buscar
        List<Habitacion> habitacionez = null;
        Hotel hotelEncontrado = null; // Variable para almacenar la referencia al hotel encontrado

        // Buscar el hotel en el arreglo
        for (Hotel hotel : hoteles) {
            if (hotel.getNombre().equals(nombreBuscado)) {
                hotelEncontrado = hotel;
                break; // Salir del bucle si se encontró el hotel
            }
        }

        // Verificar si se encontró el hotel
        if (hotelEncontrado != null) {
            // Se encontró el hotel, puedes utilizar las habitaciones de ese hotel
            habitacionez = hotelEncontrado.getHabitaciones();
        }
        
        this.vh.habitaciones = habitacionez;
        this.vh.NombreHotel.setText(NombreHotel1.getText());
        this.vh.DescripcionHotel.setText(DescripcionHotel1.getText());
        this.vh.CorreoUser.setText(CorreoUser.getText());
        this.vh.Inicial.setText(Inicial.getText());
        
        this.vh.setVisible(true);
        this.vh.setLp(this.lp);
        this.setVisible(false);
    }//GEN-LAST:event_BtnHotel1ActionPerformed

    private void BtnHotel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHotel3ActionPerformed
        String nombreBuscado = NombreHotel3.getText(); // Obtener el nombre del hotel a buscar
        List<Habitacion> habitacionez = null;
        Hotel hotelEncontrado = null; // Variable para almacenar la referencia al hotel encontrado

        // Buscar el hotel en el arreglo
        for (Hotel hotel : hoteles) {
            if (hotel.getNombre().equals(nombreBuscado)) {
                hotelEncontrado = hotel;
                break; // Salir del bucle si se encontró el hotel
            }
        }

        // Verificar si se encontró el hotel
        if (hotelEncontrado != null) {
            // Se encontró el hotel, puedes utilizar las habitaciones de ese hotel
            habitacionez = hotelEncontrado.getHabitaciones();
        }
        
        this.vh.habitaciones = habitacionez;
        this.vh.NombreHotel.setText(NombreHotel3.getText());
        this.vh.DescripcionHotel.setText(DescripcionHotel3.getText());
        this.vh.CorreoUser.setText(CorreoUser.getText());
        this.vh.Inicial.setText(Inicial.getText());
        
        this.vh.setVisible(true);
        this.vh.setLp(this.lp);
        this.setVisible(false);
    }//GEN-LAST:event_BtnHotel3ActionPerformed

    private void RegresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarBtnActionPerformed
    
        this.lp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegresarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCiudad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alojamientos;
    private javax.swing.JButton BtnHotel1;
    private javax.swing.JButton BtnHotel2;
    private javax.swing.JButton BtnHotel3;
    public javax.swing.JLabel CorreoUser;
    public javax.swing.JLabel DescripcionCiudad;
    private javax.swing.JLabel DescripcionHotel1;
    private javax.swing.JLabel DescripcionHotel2;
    private javax.swing.JLabel DescripcionHotel3;
    public javax.swing.JPanel Icono;
    public javax.swing.JLabel Inicial;
    public javax.swing.JLabel Label13;
    private javax.swing.JLabel LabelHabitacion3;
    private javax.swing.JLabel LabelNro2;
    public javax.swing.JLabel NombreCiudad;
    public javax.swing.JLabel NombreHotel1;
    public javax.swing.JLabel NombreHotel2;
    public javax.swing.JLabel NombreHotel3;
    public javax.swing.JLabel NroHabitacionesHotel1;
    public javax.swing.JLabel NroHabitacionesHotel2;
    public javax.swing.JLabel NroHabitacionesHotel3;
    private javax.swing.JLabel NumHotelesEncontrados;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JButton RegresarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    
}
